Repository LibreSign/libresign, pull requests merged in 2021-03, with the labels that each got.

#100 Feature publish app
  .github/workflows/build-release.yml
  Makefile
  package-lock.json
  package.json
Labels: backend, enhancement

#101 Clean package.json
  package.json
Labels: bug, frontend

#108 Bump version
  appinfo/info.xml
Labels: backend

#109 Add route me
  appinfo/routes.php
  lib/Controller/WebhookController.php
Labels: backend, enhancement

#110 Rename property
  lib/Controller/AdminController.php
  lib/Controller/SignatureController.php
  lib/Service/AdminSignatureService.php
Labels: backend, enhancement

#111 Remove unused var
  lib/Controller/AccountController.php
Labels: backend, enhancement

#112 Catch error
  lib/Handler/CfsslHandler.php
Labels: backend, enhancement

#113 Add health check
  lib/Handler/CfsslHandler.php
  lib/Service/AdminSignatureService.php
Labels: backend, enhancement

#114 Changelog
  CHANGELOG.md
Labels: backend, documentation

#115 Review frontend translations
  src/Components/Description/Description.vue
  src/views/CreateUser.vue
  src/views/FormLibresign.vue
  src/views/LibresignTab.vue
Labels: enhancement, frontend

#116 Backend translations
  .gitignore
  .l10nignore
  appinfo/info.xml
  lib/Controller/LibresignController.php
  lib/Helper/JSConfigHelper.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
  translationfiles/templates/libresign.pot
Labels: backend, enhancement

#117 Bump release
  CHANGELOG.md
  appinfo/info.xml
Labels: backend

#119 Fix transifex config
  .tx/config
Labels: backend, bug

#122 Update README.md
  README.md
Labels: documentation

#123 Instructions to create cfssl folder
  README.md
Labels: documentation

#124 Only include line if necessary
  README.md
Labels: documentation

#125 Changelog
  .github/workflows/changelog-enforcer.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: backend, documentation

#126 Update info.xml
  .github/workflows/changelog-enforcer.yml
  appinfo/info.xml
Labels: documentation

#132 l10n: Change to singular
  lib/Controller/LibresignController.php
Labels: backend, enhancement

#136 Change text
  lib/Controller/LibresignController.php
Labels: backend, enhancement

#129 Custom validation site
  lib/Controller/LibresignController.php
Labels: backend, enhancement

#128 Update info xml
  appinfo/info.xml
Labels: backend, documentation

#98 Create user design color
  img/bg.jpg
  img/bgCreateUser-mobile.jpg
  img/bgCreateUser.jpg
  src/assets/styles/CreateUser.scss
  src/views/CreateUser.vue
Labels: enhancement, frontend

#149 Change var name and fix translation
  src/views/LibresignTab.vue
Labels: enhancement, frontend

#151 Fix definition
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: enhancement

#153 Fix text
  src/views/LibresignTab.vue
Labels: enhancement, frontend

#154 Fix text
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: documentation

#155 Fix text
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: enhancement

#157 Improvement in text
  src/views/DefaultPageError.vue
Labels: enhancement

#152 Api documentation
  Makefile
  README.md
  appinfo/info.xml
  composer.json
  docs/.vuepress/config.js
  docs/api/README.md
  docs/package-lock.json
  docs/package.json
  docs/src/specs/api.yaml
  lib/Command/DocsSwaggerGen.php
  lib/Controller/WebhookController.php
Labels: backend, documentation
