Repository LibreSign/libresign, pull requests merged in 2021-02, with the labels that each got.

#45 Refactor rename field
  docs/API.md
  lib/Db/FileUser.php
  lib/Helper/JSConfigHelper.php
  lib/Migration/Version1000Date20210209004203.php
  lib/Migration/Version1000Date20210209011129.php
  lib/Service/MailService.php
  lib/Service/WebhookService.php
Labels: backend

#47 Ident
  docs/API.md
Labels: backend

#48 Rename field
  appinfo/routes.php
  lib/Controller/AccountController.php
  lib/Controller/LibresignController.php
  lib/Db/File.php
  lib/Db/FileMapper.php
  lib/Db/FileUser.php
  lib/Helper/JSConfigHelper.php
  lib/Migration/Version1000Date20210209004203.php
  lib/Migration/Version1000Date20210209011129.php
  lib/Service/MailService.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/AccountControllerTest.php
  tests/Unit/Service/MailServiceTest.php
Labels: backend

#49 Fix much bugs
  lib/Controller/WebhookController.php
  lib/Service/AccountService.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, bug

#50 Interaction with the api
  src/assets/images/sad-face-in-rounded-square.svg
  src/external.js
  src/middlewares/searchAction.js
  src/router/external.js
  src/router/index.js
  src/router/router.js
  src/views/AdminFormLibresign.vue
  src/views/CreateUser.vue
  src/views/DefaultPageError.vue
  src/views/FormLibresign.vue
  src/views/LibresignTab.vue
  src/views/SignPDF.vue
Labels: frontend

#57 Documentation
  .github/workflows/deploy-docs.yml
  .gitignore
  Makefile
  docs/.vuepress/config.js
  docs/Getting-started.md
  docs/README.md
  docs/package-lock.json
  docs/package.json
  docs/pt/Getting-started.md
  docs/pt/README.md
Labels: documentation

#59 Bump max nextloud version
  appinfo/info.xml
Labels: backend

#56 Feature notify callback
  lib/Controller/LibresignController.php
  lib/Db/FileUserMapper.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/LibresignControllerTest.php
Labels: backend

#54 Test libraries
  cypress.json
  jest.config.js
  lib/Helper/JSConfigHelper.php
  package-lock.json
  package.json
  src/Components/Description/Description.vue
  src/middlewares/searchAction.js
  src/router/router.js
  src/views/AllowedGroups.vue
  src/views/CreateUser.vue
  src/views/SignPDF.vue
  tests/Unit/example.spec.js
  tests/e2e/.eslintrc.js
  tests/e2e/plugins/index.js
  tests/e2e/specs/home.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
Labels: frontend

#61 bugfix route
  src/App.vue
  src/middlewares/SelectAction.js
  src/router/router.js
  src/views/CreateSubscription.vue
  src/views/SignPDF.vue
Labels: bug

#63 Fix invalid route
  lib/Helper/JSConfigHelper.php
Labels: backend, bug

#67 Translated texts and change in the error toast message.
  src/views/CreateUser.vue
Labels: frontend

#68 Disable button if sign sucess, show toast error if has error message
  src/Components/Description/Description.vue
Labels: frontend

#69 Now it is possible to view the pdf
  src/Components/PDFViewer/PDFViewer.vue
  src/views/SignPDF.vue
Labels: frontend

#74 patch sign request and move description to relation beetwen user and file
  appinfo/routes.php
  lib/Controller/AccountController.php
  lib/Controller/WebhookController.php
  lib/Db/File.php
  lib/Db/FileMapper.php
  lib/Db/FileUser.php
  lib/Helper/JSConfigHelper.php
  lib/Migration/Version1000Date20210209004203.php
  lib/Migration/Version1000Date20210209011129.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/AccountControllerTest.php
Labels: backend

#75 Bugfix last commit
  lib/Controller/WebhookController.php
Labels: backend, bug

#76 error handler
  lib/Controller/LibresignController.php
Labels: backend, bug

#77 Show error when user already signed the file
  lib/Helper/JSActions.php
  lib/Helper/JSConfigHelper.php
  lib/Service/WebhookService.php
Labels: backend, enhancement

#80 Delete sign request
  appinfo/routes.php
  lib/Controller/WebhookController.php
  lib/Db/FileUserMapper.php
  lib/Service/FolderService.php
  lib/Service/WebhookService.php
Labels: backend, enhancement

#79 Success default page
  img/frame4.png
  src/App.vue
  src/Components/Description/Description.vue
  src/Components/Description/index.js
  src/Components/Description/styles.scss
  src/Components/PDFViewer/PDFViewer.vue
  src/Components/PDFViewer/index.js
  src/assets/styles/index.css
  src/external.js
  src/main.js
  src/middlewares/SelectAction.js
  src/router/index.js
  src/router/router.js
  src/settings.js
  src/store/index.js
  src/tab.js
  src/views/AdminFormLibresign.vue
  src/views/AllowedGroups.vue
  src/views/CreateSubscription.vue
  src/views/CreateUser.vue
  src/views/DefaultPageError.vue
  src/views/DefaultPageSuccess.vue
  src/views/FormLibresign.vue
  src/views/LibresignTab.vue
  src/views/Settings.vue
  src/views/SignPDF.vue
Labels: enhancement, frontend

#81 Cancel sign notification
  lib/Controller/WebhookController.php
  lib/Service/MailService.php
Labels: backend, enhancement

#82 Validate user
  lib/Db/FileUserMapper.php
  lib/Helper/JSConfigHelper.php
Labels: backend, bug

#83 Redux Struture for persistence of data
  src/Components/Description/styles.scss
  src/external.js
  src/middlewares/SelectAction.js
  src/store/index.js
  src/views/CreateUser.vue
  src/views/SignPDF.vue
Labels: frontend

#84 fix validate user
  lib/Helper/JSConfigHelper.php
Labels: backend, bug

#87 Bugfix:return url of PDF when create user
  lib/Controller/AccountController.php
  tests/Unit/Controller/AccountControllerTest.php
Labels: backend, bug

#88 Fix widthh description
  src/Components/Description/styles.scss
Labels: bug, frontend

#89 Send mail when change sign request
  lib/Controller/LibresignController.php
  lib/Controller/WebhookController.php
  lib/Service/MailService.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#91 Add CSP
  lib/Controller/PageController.php
Labels: backend, bug

#92 Fix Did not access the subscription page after creating the user and …
  src/Components/Description/styles.scss
  src/views/CreateUser.vue
Labels: bug, frontend
