Repository LibreSign/libresign, pull requests merged in 2021-06, with the labels that each got.

#264 Increment coverage and refactors
  CHANGELOG.md
  composer.json
  composer.lock
  docs/.vuepress/public/specs/api.yaml
  lib/Controller/AccountController.php
  lib/Controller/AdminController.php
  lib/Controller/HandleErrorsTrait.php
  lib/Controller/LibresignController.php
  lib/Controller/SignatureController.php
  lib/Controller/WebhookController.php
  lib/Service/AccountService.php
  lib/Service/AdminSignatureService.php
  lib/Service/FolderService.php
  lib/Service/MailService.php
  lib/Service/WebhookService.php
  tests/Unit/ApiRequester.php
  tests/Unit/ApiTestCase.php
  tests/Unit/Controller/AccountControllerTest.php
  tests/Unit/Controller/AdminControllerTest.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Controller/SignatureControllerTest.php
  tests/Unit/Controller/WebhookControllerTest.php
  tests/Unit/Handler/CfsslHandlerTest.php
  tests/Unit/Handler/JLibresignHandlerTest.php
  tests/Unit/LibresignFileTrait.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/LibresignServiceTest.php
  tests/Unit/Service/MailServiceTest.php
  tests/Unit/Service/SignatureServiceTest.php
  tests/Unit/Service/WebhookServiceTest.php
  tests/Unit/Settings/AdminSettingsTest.php
  tests/Unit/Settings/AdminTest.php
  tests/Unit/TestCase.php
  tests/Unit/UserTrait.php
  tests/dredd/hooks/hookfile.php
  tests/fixtures/cfssl/newcert-with-success.json
  tests/fixtures/small_valid.pdf
  tests/lib/AppConfigOverwrite.php
  tests/lib/AppConfigOverwrite20.php
Labels: backend, enhancement

#267 Test coverage on page controller
  CHANGELOG.md
  lib/Controller/PageController.php
  lib/Service/AccountService.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/UserTrait.php
Labels: backend, enhancement

#270 Increase coverage page controller
  CHANGELOG.md
  lib/Controller/PageController.php
  lib/Service/AccountService.php
  lib/Service/WebhookService.php
  tests/Unit/ApiTestCase.php
  tests/Unit/Controller/AdminControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/LibresignFileTrait.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/WebhookServiceTest.php
  tests/Unit/TestCase.php
  tests/Unit/UserTrait.php
Labels: backend, enhancement

#272 Add approval
  CHANGELOG.md
  README.md
Labels: documentation, enhancement

#274 Use name on empty email
  CHANGELOG.md
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#277 Moving site to another repository
  .github/workflows/deploy-docs.yml
  .github/workflows/phpunit.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/public/specs/api.yaml
  docs/Getting-started.md
  docs/README.md
  docs/api/README.md
  docs/package.json
  docs/pt/Getting-started.md
  docs/pt/README.md
  docs/pt/api/README.md
  docs/yarn.lock
  tests/Unit/ApiTestCase.php
Labels: documentation

#275 Endpoint to list LibreSign docs
  .github/workflows/phpunit.yml
  .gitignore
  CHANGELOG.md
  appinfo/routes.php
  lib/Controller/LibresignController.php
  lib/Controller/WebhookController.php
  lib/Db/FileUserMapper.php
  lib/Db/ReportDao.php
  lib/Service/AccountService.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/AccountControllerTest.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Controller/WebhookControllerTest.php
  tests/Unit/LibresignFileTrait.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/WebhookServiceTest.php
  tests/Unit/UserTrait.php
Labels: backend, enhancement

#265 Interface to list docs
  .gitignore
  CHANGELOG.md
  src/App.vue
  src/Components/File/File.vue
  src/Components/File/Sidebar.vue
  src/Components/File/SignaturesTab.vue
  src/Components/File/index.js
  src/router/router.js
  src/store/index.js
  src/views/LibresignTab.vue
  src/views/Timeline.vue
Labels: enhancement, frontend

#287 Changed for loading class after click for sign
  CHANGELOG.md
  src/Components/File/Sidebar.vue
  src/Components/InputAction/InputAction.vue
  src/Components/Sign/Sign.vue
  src/views/Timeline.vue
Labels: enhancement, frontend

#288 Fix css sign
  CHANGELOG.md
  jest.config.js
  jsconnfig.json
  package.json
  src/Components/File/File.vue
  src/__test__/unit/App.spec.js
  yarn.lock
Labels: enhancement, frontend

#291 Delete old logo
  CHANGELOG.md
  img/app-dark-old.svg
  img/app-old.svg
Labels: enhancement

#296 Menu to validate
  CHANGELOG.md
  src/App.vue
Labels: enhancement, frontend

#289 Request Subscription By LibreSign App
  CHANGELOG.md
  src/App.vue
  src/Components/File/File.vue
  src/Components/ListItem/ListItem.vue
  src/router/router.js
  src/store/index.js
  src/views/Request.vue
Labels: enhancement, frontend

#298 Bump max Nextcloud supported version
  .github/workflows/phpunit.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: enhancement

#299 lint on php8
  .github/workflows/lint.yml
Labels: backend, enhancement

#300 Refactor
  lib/Controller/SignFileController.php
  lib/Db/FileMapper.php
  lib/Handler/JLibresignHandler.php
  lib/Handler/PkcsHandler.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  phpunit.xml
  tests/Api/ApiRequester.php
  tests/Api/ApiTestCase.php
  tests/Api/Controller/AccountControllerTest.php
  tests/Api/Controller/AdminControllerTest.php
  tests/Api/Controller/LibresignControllerTest.php
  tests/Api/Controller/SettingControllerTest.php
  tests/Api/Controller/SignFileControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/SignFileControllerTest.php
  tests/Unit/Handler/PkcsHandlerTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/SignFileServiceTest.php
  tests/Unit/UserTrait.php
Labels: backend, enhancement

#304 Confirm password
  CHANGELOG.md
  package.json
  src/App.vue
  src/Components/Settings/CroppedLayoutSettings.vue
  src/Components/Sign/Sign.vue
  src/Components/Sign/styles.scss
  src/main.js
  src/router/router.js
  src/store/index.js
  src/views/Account.vue
  src/views/CreatePassword.vue
  src/views/ResetPassword.vue
  yarn.lock
Labels: enhancement, frontend

#297 User profile
  CHANGELOG.md
Labels: enhancement, frontend, good first issue

#303 Refactor and wip to implement sign any file
  appinfo/routes.php
  lib/Controller/AccountDeprecatedController.php
  lib/Controller/AdminController.php
  lib/Controller/PageController.php
  lib/Controller/SettingDeprecatedController.php
  lib/Controller/SignFileController.php
  lib/Controller/SignFileDeprecatedController.php
  lib/Handler/JSignPdfHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Handler/Pkcs7Handler.php
  lib/Service/AccountService.php
  lib/Service/AdminSignatureService.php
  lib/Service/FolderService.php
  lib/Service/SignFileService.php
  src/views/CreateSubscription.vue
  src/views/LibresignTab.vue
  src/views/LibresignTab20.vue
  src/views/Request.vue
  tests/Api/Controller/SignFileControllerTest.php
  tests/Unit/Controller/SignFileControllerTest.php
  tests/Unit/Handler/JSignPdfHandler.php
  tests/Unit/Handler/Pkcs12HandlerTest.php
  tests/Unit/Handler/PkcsHandlerTest.php
  tests/Unit/Helper/ValidateHelperTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/FolderServiceTest.php
  tests/Unit/Service/SignFileServiceTest.php
  tests/Unit/UserTrait.php
Labels: backend, enhancement

#306 Fix request inside folder
  CHANGELOG.md
  src/views/Request.vue
Labels: bug, frontend, team

#307 Fix validation
  CHANGELOG.md
  src/views/Validation.vue
Labels: bug, frontend, team

#308 Filter files
  CHANGELOG.md
  src/Components/File/Sidebar.vue
  src/views/Timeline.vue
Labels: enhancement, frontend, team

#309 Bufixes
  lib/Controller/LibresignController.php
  lib/Handler/Pkcs7Handler.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  tests/Unit/Handler/Pkcs7HandlerTest.php
  tests/Unit/Service/AccountServiceTest.php
Labels: backend, bug, team

#310 Check has pfx
  CHANGELOG.md
  src/Components/File/SignaturesTab.vue
  src/Components/InputAction/InputAction.vue
  src/Components/Sign/Sign.vue
  src/views/CreatePassword.vue
Labels: enhancement, frontend, team

#311 fix check if have pfx.
  src/Components/Sign/Sign.vue
  src/Components/Sign/styles.scss
Labels: enhancement, frontend, team

#312 l10n: Add dots
  src/Components/Sign/Sign.vue
Labels: community
