Repository LibreSign/libresign, pull requests merged in 2021-10, with the labels that each got.

#407 Feature/visible elements tests
  composer.lock
  lib/Controller/SignFileController.php
  lib/Controller/SignFileDeprecatedController.php
  lib/Helper/ValidateHelper.php
  lib/Service/SignFileService.php
  src/assets/fonts/DancingScript/DancingScript.ttf
  src/views/Account.vue
  tests/Unit/Helper/ValidateHelperTest.php
  tests/Unit/Service/SignFileServiceTest.php
Labels: enhancement, backend

#424 Feature/accounts create visible signature 396
  CHANGELOG.md
  src/Components/Draw/Draw.vue
  src/store/index.js
  src/store/modules/modal.js
  src/store/modules/signatures.js
  src/views/Account.vue
  src/views/Account/Account.vue
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/Signatures.vue
  src/views/Account/partials/UserImage.vue
Labels: frontend

#425 Add status to LibreSign file
  CHANGELOG.md
  lib/Controller/LibreSignFileController.php
  lib/Controller/SignFileController.php
  lib/Controller/SignFileDeprecatedController.php
  lib/Db/File.php
  lib/Db/FileMapper.php
  lib/Helper/ValidateHelper.php
  lib/Migration/Version2040Date20211030204227.php
  lib/Service/SignFileService.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/SignFileServiceTest.php
Labels: enhancement, backend

#426 Change image url
  lib/Service/AccountService.php
Labels: enhancement, backend

#427 Feature/accounts create visible signature 396
  .eslintrc.js
  CHANGELOG.md
  package.json
  src/Components/Description/Description.vue
  src/Components/Draw/Draw.vue
  src/Components/PDFViewer/PDFViewer.vue
  src/Components/PDFViewer/Tools.vue
  src/Components/Sign/Sign.vue
  src/assets/images/zoom_in.png
  src/assets/images/zoom_out.png
  src/domains/sign/index.js
  src/domains/sign/service.js
  src/domains/signatures/index.js
  src/domains/signatures/service.js
  src/external.js
  src/helpers/SelectAction.js
  src/helpers/path.js
  src/main.js
  src/router/index.js
  src/router/router.js
  src/services/FilesService.js
  src/services/FilesService.spec.js
  src/services/InitialStateService.js
  src/services/InitialStateService.spec.js
  src/store/index.js
  src/store/modules/feature_controller.js
  src/store/modules/files.js
  src/store/modules/modal.js
  src/store/modules/signatures.js
  src/store/modules/user.js
  src/views/Account.vue
  src/views/Account/Account.vue
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/Signatures.vue
  src/views/Account/partials/UserImage.vue
  src/views/CreateUser.vue
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF.vue
  yarn.lock
Labels: frontend, hacktoberfest-accepted

#428 UX adjusts
  .eslintrc.js
  CHANGELOG.md
  appinfo/routes.php
  lib/Controller/LibreSignFileController.php
  lib/Controller/PageController.php
  lib/Controller/SignFileController.php
  lib/Controller/SignFileDeprecatedController.php
  lib/Db/File.php
  lib/Db/FileMapper.php
  lib/Helper/ValidateHelper.php
  lib/Migration/Version2040Date20211030204227.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  package.json
  src/Components/Description/Description.vue
  src/Components/PDFViewer/PDFViewer.vue
  src/domains/sign/index.js
  src/domains/sign/service.js
  src/domains/signatures/index.js
  src/domains/signatures/service.js
  src/helpers/path.js
  src/router/index.js
  src/router/router.js
  src/store/index.js
  src/views/Account/Account.vue
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/Signatures.vue
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF.vue
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/SignFileServiceTest.php
  yarn.lock
Labels: backend, frontend

#423 [WIP] Release/v2.5
  CHANGELOG.md
  appinfo/routes.php
  src/router/index.js
  src/router/router.js
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/Signatures.vue
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF.vue
Labels: frontend, hacktoberfest-accepted
