Repository LibreSign/libresign, pull requests merged in 2021-09, with the labels that each got.

#374 Migrate from FPDI to TCPDF
  CHANGELOG.md
  composer.json
  composer.lock
  lib/Handler/ISignHandler.php
  lib/Handler/JSignPdfHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Handler/TCPDILibresign.php
  lib/Helper/ValidateHelper.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  tests/Api/Controller/SignFileControllerTest.php
  tests/Unit/Handler/Pkcs12HandlerTest.php
  tests/Unit/Helper/ValidateHelperTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/SignFileServiceTest.php
Labels: enhancement, backend

#392 Refactor Store
  jsconfig.json
  src/Components/Description/Description.vue
  src/Components/File/Sidebar.vue
  src/Components/File/SignaturesTab.vue
  src/Components/Sign/Sign.vue
  src/__test__/unit/Timeline.spec.js
  src/router/router.js
  src/store/index.js
  src/store/modules/errors.js
  src/store/modules/files.js
  src/store/modules/sidebar.js
  src/store/modules/sign.js
  src/store/modules/validate.js
  src/views/DefaultPageError.vue
  src/views/DefaultPageSuccess.vue
  src/views/Request.vue
  src/views/Timeline.vue
Labels: frontend, team

#404 Controller features
  CHANGELOG.md
  src/init.js
  src/main.js
  src/settings.js
  src/store/index.js
  src/store/modules/f_controller.js
Labels: enhancement, frontend
