Repository LibreSign/libresign, pull requests merged in 2021-07, with the labels that each got.

#315 Create app config to configure jsignpdf
  CHANGELOG.md
  lib/Handler/JSignPdfHandler.php
Labels: backend, enhancement

#318 Pagination
  Makefile
  composer.json
  composer.lock
  lib/Controller/LibreSignFileController.php
  lib/Db/PagerFantaQueryAdapter.php
  lib/Db/ReportDao.php
  lib/Helper/Pagination.php
  lib/Service/AccountService.php
  lib/Service/AdminSignatureService.php
  tests/Unit/Helper/PaginationHelperTest.php
Labels: backend, enhancement, team

#320 Rename test file
  tests/Unit/Handler/JSignPdfHandlerTest.php
Labels: backend, enhancement

#323 Make possible change CFSSL properties
  CHANGELOG.md
  lib/Handler/CfsslHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Handler/SignEngineInterface.php
  lib/Service/AccountService.php
  tests/Unit/Service/AccountServiceTest.php
Labels: backend, enhancement

#327 Update CHANGELOG.md
  CHANGELOG.md
Labels: backport-request, documentation

#331 Change text
  CHANGELOG.md
  appinfo/info.xml
  lib/Helper/ValidateHelper.php
  tests/Unit/Helper/ValidateHelperTest.php
Labels: backend, enhancement

#333 Enables viewing the pdf when on mobile.
  CHANGELOG.md
  src/Components/Description/Description.vue
  src/Components/Description/styles.scss
  src/views/SignPDF.vue
Labels: enhancement, frontend, good first issue, team

#335 Show request button if file not signed
  src/views/LibresignTab.vue
Labels: enhancement, frontend, good first issue, team

#336 add markdown to description
  .eslintrc.js
  CHANGELOG.md
  package.json
  src/Components/Description/Description.vue
  src/Components/ListItem/ListItem.vue
  yarn.lock
Labels: bug, frontend

#350 Preview document
  CHANGELOG.md
  src/Components/File/Sidebar.vue
  src/views/Timeline.vue
Labels: enhancement, frontend

#351 Legal information
  CHANGELOG.md
  src/assets/styles/validation.scss
  src/views/Settings.vue
  src/views/Validation.vue
Labels: enhancement, frontend
