Repository LibreSign/libresign, pull requests merged in 2021-05, with the labels that each got.

#212 Sign using nodeid
  docs/Getting-started.md
  lib/Service/AccountService.php
  lib/Service/FolderService.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#213 Change property name
  docs/Getting-started.md
  lib/Service/WebhookService.php
Labels: backend, documentation, enhancement

#215 Improvements in validate file_id
  lib/Db/FileMapper.php
  lib/Service/FolderService.php
  lib/Service/WebhookService.php
Labels: backend, enhancement

#218 Changed the package manager from npm to yarn.
  Makefile
  docs/package-lock.json
  docs/yarn.lock
  package-lock.json
  yarn.lock
Labels: frontend

#219 Swagger
  Makefile
  appinfo/info.xml
  composer.json
  composer.lock
  docs/.vuepress/config.js
  docs/.vuepress/public/specs/api.yaml
  docs/Getting-started.md
  docs/README.md
  docs/api/README.md
  docs/package.json
  docs/pt/Getting-started.md
  docs/pt/README.md
  docs/pt/api/README.md
  docs/src/specs/api.yaml
  docs/yarn.lock
  lib/Command/DocsSwaggerGen.php
  lib/Controller/WebhookController.php
Labels: backend, documentation

#220 Document sing and validate methods
  docs/.vuepress/public/specs/api.yaml
  lib/Controller/LibresignController.php
  lib/Controller/WebhookController.php
Labels: backend, documentation

#224 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#223 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#226 Coverage improvement
  .github/workflows/phpunit.yml
  README.md
  composer.lock
  tests/Unit/Controller/AccountControllerTest.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/LibresignServiceTest.php
  tests/Unit/Service/MailServiceTest.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#227 Bugfix generate password
  lib/Controller/AccountController.php
  lib/Handler/CfsslHandler.php
  lib/Service/AccountService.php
  src/views/FormLibresign.vue
  tests/Unit/Controller/AccountControllerTest.php
  tests/Unit/Service/AccountServiceTest.php
Labels: backend, bug

#228 Coverage improvement
  tests/Unit/Service/AccountServiceTest.php
Labels: backend, enhancement

#206 LibreSign signature validation
  .eslintrc.js
  .gitignore
  README.md
  appinfo/routes.php
  docs/.vuepress/public/specs/api.yaml
  img/file-signature-solid.svg
  img/info-circle-solid.svg
  lib/AppInfo/Application.php
  lib/Controller/AccountController.php
  lib/Controller/LibresignController.php
  lib/Controller/PageController.php
  lib/Controller/WebhookController.php
  lib/Db/FileMapper.php
  lib/Db/FileUserMapper.php
  lib/Helper/JSConfigHelper.php
  lib/Migration/Version1000Date20210502200600.php
  lib/Migration/Version1000Date20210502200800.php
  lib/Service/WebhookService.php
  package.json
  src/Components/Description/Description.vue
  src/Components/InputAction/InputAction.vue
  src/Components/InputAction/index.js
  src/Components/InputAction/styles.scss
  src/Components/ListItem/ListItem.vue
  src/Components/ListItem/index.js
  src/Components/ListItem/styles.scss
  src/Components/PDFViewer/PDFViewer.vue
  src/Components/PDFViewer/styles.scss
  src/Components/Request/Request.vue
  src/Components/Request/index.js
  src/Components/Request/styles.scss
  src/Components/Sign/Sign.vue
  src/Components/Sign/index.js
  src/Components/Sign/styles.scss
  src/assets/images/bg.png
  src/assets/images/signed-icon.svg
  src/assets/styles/validation.scss
  src/helpers/SelectAction.js
  src/router/index.js
  src/router/router.js
  src/store/index.js
  src/utils/validators.js
  src/views/FormLibresign.vue
  src/views/LibresignTab.vue
  src/views/Validation.vue
  templates/validation.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Service/WebhookServiceTest.php
  yarn.lock
Labels: backend, enhancement, frontend

#229 Fix extraneous-import error
  .eslintrc.js
Labels: bug, frontend

#233 Update swagger
  docs/.vuepress/public/specs/api.yaml
Labels: bug, documentation

#231 Coverage improvement
  lib/Controller/SignatureController.php
  lib/Service/SignatureService.php
  lib/Service/WebhookService.php
  phpunit.xml
  tests/Unit/Service/SignatureServiceTest.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#237 Coverage improvement
  lib/Controller/WebhookController.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#239 Coverage improvement
  lib/AppInfo/Application.php
  lib/Db/FileMapper.php
  lib/Db/FileUserMapper.php
  lib/Exception/LibresignException.php
  lib/Handler/JLibresignHandler.php
  lib/Listener/LoadSidebarListener.php
  tests/Unit/Handler/JLibresignHandlerTest.php
  tests/Unit/Settings/AdminSettingsTest.php
  tests/Unit/Settings/AdminTest.php
Labels: backend, enhancement

#238 Remove unused file
  tests/Unit/example.spec.js
Labels: frontend

#240 Coverage improvement
  lib/Handler/CfsslHandler.php
  tests/Unit/Handler/CfsslHandlerTest.php
  tests/Unit/Handler/JLibresignHandlerTest.php
  tests/Unit/Handler/mock/cert.json
  tests/Unit/Settings/AdminSettingsTest.php
  tests/Unit/Settings/AdminTest.php
Labels: backend, enhancement

#236 Signature password
  appinfo/routes.php
  docs/.vuepress/public/specs/api.yaml
  lib/Controller/LibresignController.php
  lib/Controller/PageController.php
  lib/Helper/JSActions.php
  lib/Service/AccountService.php
  src/Components/ConfirmPassword/Confirm.vue
  src/Components/Description/Description.vue
  src/Components/Description/styles.scss
  src/Components/Input/Input.vue
  src/Components/InputAction/InputAction.vue
  src/Components/Request/Request.vue
  src/Components/Sign/Sign.vue
  src/Components/Sign/styles.scss
  src/router/index.js
  src/router/router.js
  src/views/CreatePassword.vue
  src/views/FormLibresign.vue
  src/views/LibresignTab.vue
  src/views/ResetPassword.vue
  templates/reset_password.php
  tests/Unit/Service/AccountServiceTest.php
Labels: enhancement, frontend

#241 Add Home
  src/App.vue
  src/Components/Settings/CroppedLayoutSettings.vue
  src/router/router.js
Labels: enhancement, frontend

#247 Fix message in the home page app
  src/App.vue
Labels: frontend

#248 Add has signature file check
  lib/Controller/PageController.php
  src/Components/Settings/CroppedLayoutSettings.vue
  src/store/index.js
  src/views/CreatePassword.vue
Labels: backend, enhancement, frontend

#253 Chagnelog
  CHANGELOG.md
Labels: documentation, enhancement

#251 Add changelog-reminder.yml
  .github/changelog-ci-config.yml
  .github/workflows/changelog-reminder.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
Labels: enhancement

#257 Remove dsv
  CHANGELOG.md
  dsv/.gitignore
  dsv/LICENSE
  dsv/README.md
  dsv/appinfo/app.php
  dsv/appinfo/info.xml
  dsv/appinfo/routes.php
  dsv/css/tabview.css
  dsv/js/plugin.js
  dsv/js/tabview.js
  dsv/lib/AppInfo/Application.php
  dsv/lib/Controller/DsvController.php
  dsv/lib/Service/DsvService.php
  dsv/lib/Service/PdfSig.php
  dsv/lib/composer.json
  dsv/lib/composer.lock
Labels: enhancement

#254 script version based on nextcloud version
  lib/Listener/LoadSidebarListener.php
  src/tab-20.js
Labels: backend, enhancement

#260 Fix method name
  CHANGELOG.md
  lib/Db/FileUserMapper.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, bug

#261 Fix tests autoload
  CHANGELOG.md
  lib/Controller/LibresignController.php
  lib/Handler/CfsslHandler.php
  lib/Service/WebhookService.php
  tests/Unit/Controller/LibresignControllerTest.php
  tests/Unit/Handler/CfsslHandlerTest.php
  tests/Unit/Service/WebhookServiceTest.php
  tests/bootstrap.php
  tests/dredd/hooks/hookfile.php
Labels: backend, bug

#263 Test for validation of Swagger documentation
  .github/workflows/phpunit.yml
  CHANGELOG.md
  composer.json
  composer.lock
  lib/Controller/SignatureController.php
  tests/Unit/ApiRequester.php
  tests/Unit/ApiTestTrait.php
  tests/Unit/Controller/SignatureControllerTest.php
  tests/Unit/UserTrait.php
  tests/bootstrap.php
Labels: backend, documentation
