Repository LibreSign/libresign, pull requests merged in 2021-08, with the labels that each got.

#355 Associate signed file to libresign file
  CHANGELOG.md
  lib/Db/File.php
  lib/Db/FileMapper.php
  lib/Handler/Pkcs12Handler.php
  lib/Migration/Version2040Date20210730022217.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  tests/Unit/Service/AccountServiceTest.php
Labels: backend, bug

#368 Button for validating the document after signing.
  CHANGELOG.md
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF.vue
  src/views/Validation.vue
Labels: bug, frontend

#369 Reload after signing the document
  CHANGELOG.md
  src/views/LibresignTab.vue
  src/views/Validation.vue
Labels: frontend

#370 Validation UUID
  CHANGELOG.md
  src/Components/Description/Description.vue
  src/assets/styles/CreateUser.scss
  src/assets/styles/validation.scss
  src/router/router.js
  src/store/index.js
  src/views/CreateUser.vue
  src/views/DefaultPageSuccess.vue
  src/views/Request.vue
  src/views/Validation.vue
Labels: bug, frontend

#372 responsive components
  src/assets/styles/validation.scss
Labels: bug, frontend

#373 Validate byuuid or bynodeid
  CHANGELOG.md
  src/views/LibresignTab.vue
  src/views/Validation.vue
Labels: enhancement, frontend

#376 Wizard create user
  CHANGELOG.md
  src/assets/styles/CreateUser.scss
  src/assets/styles/validation.scss
  src/views/CreateUser.vue
Labels: enhancement, frontend

#337 LibreSign button to Files
  CHANGELOG.md
  src/tab.js
Labels: enhancement, frontend

#391 Fix check validate button files plugin
  CHANGELOG.md
  src/App.vue
  src/Components/File/Sidebar.vue
  src/__test__/unit/Timeline.spec.js
  src/assets/styles/validation.scss
  src/router/router.js
  src/views/LibresignTab.vue
  src/views/Timeline.vue
  src/views/Validation.vue
Labels: bug, frontend
