Repository LibreSign/libresign, pull requests merged in 2021-04, with the labels that each got.

#162 bump setup php
  .github/workflows/phpunit.yml
Labels: backend, enhancement

#161 Validate by UUID
  appinfo/routes.php
  lib/Controller/LibresignController.php
  tests/Unit/Controller/LibresignControllerTest.php
Labels: enhancement

#163 Make validate endpoint public
  lib/Controller/LibresignController.php
Labels: backend

#164 Move settings to specific menu
  README.md
  appinfo/info.xml
  img/app-dark.svg
  lib/Settings/Admin.php
  lib/Settings/AdminSettings.php
Labels: enhancement

#174 Fix fatal error on run in cron
  lib/AppInfo/Application.php
Labels: backend, bug

#175 Make info.xml compatible with xml schema
  appinfo/info.xml
Labels: backend, bug

#176 Add app:check-code
  .github/workflows/app-check-code.yml
  lib/Controller/LibresignController.php
  lib/Helper/JSConfigHelper.php
  lib/Service/AccountService.php
  lib/Service/WebhookService.php
Labels: backend, enhancement

#177 Test matrix
  .github/workflows/phpunit.yml
  appinfo/info.xml
Labels: backend, enhancement

#179 Help to cs:fix when fail
  .github/workflows/lint.yml
Labels: backend, enhancement

#182 Prevent warning
  lib/Service/WebhookService.php
Labels: backend, bug

#184 Bugfix: concatenate
  lib/Controller/LibresignController.php
Labels: backend, bug

#185 Fix property name
  lib/Controller/AdminController.php
Labels: backend, bug

#186 Validates a PDF. Triggers error if invalid.
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, enhancement

#187 Fix get config
  lib/Controller/LibresignController.php
  tests/Unit/Controller/LibresignControllerTest.php
Labels: backend, bug

#190 Fix transifex setting
  .tx/config
Labels: bug

#193 translations
  src/views/AdminFormLibresign.vue
Labels: enhancement, frontend

#196 Force email to lowercase
  lib/Service/WebhookService.php
Labels: backend, bug

#197 Only use validate page if is defined
  lib/Controller/LibresignController.php
Labels: backend, enhancement

#199 Improvements and bugfix
  lib/Controller/LibresignController.php
  lib/Service/WebhookService.php
  tests/Unit/Service/WebhookServiceTest.php
Labels: backend, bug

#200 Return status signed
  .prettierrc
  lib/Controller/LibresignController.php
  lib/Helper/JSActions.php
  src/Components/Description/Description.vue
  webpack.dev.js
  webpack.prod.js
Labels: backend, enhancement, frontend

#204 default placeholder url
  src/views/UrlValidation.vue
Labels: enhancement, frontend
