Repository LibreSign/libresign, pull requests merged in 2022-10, with the labels that each got.

#923 Add new command to validate setup
  Makefile
  README.md
  appinfo/info.xml
  lib/Command/Configure/Check.php
  lib/Handler/CfsslHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Service/AdminSignatureService.php
  lib/Service/ConfigureCheckService.php
Labels: backport-request

#948 Download binaries during setup
  lib/Command/Configure/Cfssl.php
  lib/Controller/AdminController.php
  lib/Controller/HandleParamsTrait.php
  lib/Controller/SettingController.php
  lib/Handler/CfsslHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Service/AdminSignatureService.php
  lib/Service/InstallService.php
  tests/Unit/Handler/CfsslHandlerTest.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/PdfParseServiceTest.php
Labels: backport-request

#951 Update node workflow from template
  .github/workflows/node.properties.json
  .github/workflows/node.svg
  .github/workflows/node.yml
Labels: backport-request

#956 Composer update
  composer.json
  composer.lock
Labels: backport-request

#960 Download binaries from admin settings
  README.md
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/AdminController.php
  lib/Handler/CfsslHandler.php
  lib/Service/InstallService.php
  lib/Service/PdfParserService.php
  src/Components/File/File.vue
  src/views/Request.vue
  src/views/Settings/AdminFormLibresign.vue
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/DownloadBinaries.vue
  src/views/Settings/Settings.vue
  src/views/Timeline/Timeline.spec.js
  src/views/Timeline/Timeline.vue
  tests/Api/Controller/AdminControllerTest.php
Labels: backport-request

#968 Small improvements to download java
  lib/Service/InstallService.php
Labels: backport-request

#977 Fix field size
  src/views/Settings/AdminFormLibresign.vue
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/UrlValidation.vue
Labels: backport-request

#981 Refactor download files
  src/views/Settings/DownloadBinaries.vue
Labels: backport-request

#985 Set default value
  lib/Service/InstallService.php
Labels: backport-request

#986 Fix typo
  src/views/Settings/DownloadBinaries.vue
Labels: backport-request

#993 Implement await
  src/views/Settings/DownloadBinaries.vue
Labels: backport-request

#1002 Bump javascript packages
  package-lock.json
  package.json
Labels: backport-request

#1011 Feature/bump packages
  lib/Handler/CfsslHandler.php
  lib/Handler/JSignPdfHandler.php
  lib/Service/ConfigureCheckService.php
  lib/Service/InstallService.php
  package-lock.json
  package.json
  src/App.vue
  src/Components/ConfirmPassword/Confirm.vue
  src/Components/Draw/Editor.vue
  src/Components/Draw/FileUpload.vue
  src/Components/Draw/TextInput.vue
  src/Components/File/Sidebar.vue
  src/Components/File/SignaturesTab.vue
  src/Components/ListItem/ListItem.vue
  src/Components/Modals/ModalContent.vue
  src/Components/Settings/CroppedLayoutSettings.vue
  src/directives/VTooltip.js
  src/domains/files/service.js
  src/domains/settings/service.js
  src/external.js
  src/main.js
  src/tab.js
  src/validation.js
  src/views/Account/Account.vue
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/UserImage.vue
  src/views/CreatePassword.vue
  src/views/CreateSubscription.vue
  src/views/CreateUser.vue
  src/views/Documents/AccountValidation.vue
  src/views/FilesTab/LibresignTab.vue
  src/views/FormLibresign.vue
  src/views/Request.vue
  src/views/ResetPassword.vue
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/ConfigureCheck.vue
  src/views/Settings/DownloadBinaries.vue
  src/views/Settings/LegalInformation.vue
  src/views/Settings/RootCertificate.vue
  src/views/Settings/Settings.vue
  src/views/Settings/UrlValidation.vue
  src/views/SignDetail/SignDetail.vue
  src/views/SignDetail/partials/PageNavigation.vue
  src/views/SignDetail/partials/SignerRow.vue
  src/views/SignPDF/_partials/ModalEmailManager.vue
  src/views/SignPDF/_partials/ModalPasswordManager.vue
  src/views/SignPDF/_partials/ModalSMSManager.vue
  src/views/Timeline/Timeline.vue
  src/views/Validation.vue
Labels: backport-request

#1019 Feature/implement frontend to change settings
  src/views/Settings/Settings.vue
  src/views/Settings/SignPage.vue
  src/views/Settings/UrlValidation.vue
Labels: backport-request

#1021 Add transparency to right tab when sign document
  src/views/SignPDF/SignPDF.vue
Labels: backport-request

#1025 FIx position of email
  src/Components/ListItem/ListItem.vue
  src/Components/ListItem/styles.scss
Labels: backport-request

#1027 Prevent delete signed data
  lib/Listener/BeforeNodeDeletedListener.php
Labels: backport-request

#1031 Change text
  src/views/Settings/ConfigureCheck.vue
Labels: backport-request

#1033 l10n: Fixed typo and grammar
  src/views/Settings/SignPage.vue
Labels: backport-request, translation

#491 l10n: Add an ellipsis
  src/views/SignPDF/_partials/Sidebar.vue
Labels: backport-request, translation

#1040 Bug Fix: Toggle Validation Site
  src/views/Settings/SignPage.vue
Labels: backport-request

#1042 Feature: translation tips
  lib/Controller/AccountController.php
Labels: backport-request

#1062 Progress bar to install
  appinfo/routes.php
  lib/Controller/AdminController.php
  lib/Service/InstallService.php
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/DownloadBinaries.vue
  tests/Api/Controller/SignFileControllerTest.php
Labels: backport-request

#1064 improvements to generate certificate
  lib/Controller/AdminController.php
  lib/Handler/CfsslServerHandler.php
  lib/Service/ConfigureCheckService.php
  src/views/Settings/DownloadBinaries.vue
  src/views/Settings/RootCertificate.vue
  src/views/Settings/Settings.vue
Labels: backport-request

#1079 Bug Fix: Install
  lib/Service/ConfigureCheckService.php
  lib/Service/InstallService.php
  src/views/Settings/DownloadBinaries.vue
  src/views/Settings/RootCertificate.vue
Labels: backport-request

#1083 Changelog
  CHANGELOG.md
Labels: backport-request

#1091 display with line break and prevent to use java when not available
  lib/Service/ConfigureCheckService.php
  lib/Service/InstallService.php
  src/views/Settings/ConfigureCheck.vue
Labels: backport-request

#1105 Make possible generate root cert with custom values
  lib/Controller/AccountController.php
  lib/Controller/AdminController.php
  lib/Handler/CfsslHandler.php
  lib/Handler/CfsslServerHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Migration/Version7000Date20221026003343.php
  lib/Service/AccountService.php
  lib/Service/AdminSignatureService.php
  lib/Service/InstallService.php
  src/views/ResetPassword.vue
  src/views/Settings/DownloadBinaries.vue
  src/views/Settings/RootCertificate.vue
  tests/Api/Controller/AccountControllerTest.php
  tests/Api/Controller/AdminControllerTest.php
  tests/Api/Controller/SignFileControllerTest.php
  tests/Unit/Service/AccountServiceTest.php
Labels: backport-request

#1117 Fix wrong migration
  appinfo/info.xml
  lib/Migration/Version7000Date20221028022904.php
Labels: bug, backport-request

#1118 Bugfix/psalm
  .github/workflows/node.properties.json
  .github/workflows/node.svg
  .github/workflows/psalm.yml
  lib/Controller/AccountController.php
  lib/Controller/AdminController.php
  lib/Controller/PageController.php
  lib/Controller/SignFileDeprecatedController.php
  lib/Db/AccountFileMapper.php
  lib/Db/File.php
  lib/Db/FileElementMapper.php
  lib/Db/FileMapper.php
  lib/Db/FileTypeMapper.php
  lib/Db/FileUserMapper.php
  lib/Db/UserElementMapper.php
  lib/Event/ASignedEvent.php
  lib/Handler/CfsslHandler.php
  lib/Handler/Pkcs12Handler.php
  lib/Listener/SignedListener.php
  lib/Migration/Version7000Date20221026003343.php
  lib/Service/AccountService.php
  lib/Service/AdminSignatureService.php
  lib/Service/FileService.php
  lib/Service/FolderService.php
  lib/Service/InstallService.php
  lib/Service/MailService.php
  lib/Service/PdfParserService.php
  lib/Service/SignFileService.php
  psalm.xml
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Handler/CfsslHandlerTest.php
  tests/Unit/Service/PdfParseServiceTest.php
  tests/Unit/TestCase.php
  tests/psalm-baseline.xml
Labels: backport-request

#1125 Fix previows commit
  lib/Migration/Version7000Date20221028022904.php
Labels: bug, backport-request
