Repository LibreSign/libresign, pull requests merged in 2023-01, with the labels that each got.

#1327 Update dependabot-approve.yml
  .github/workflows/dependabot-approve.yml
Labels: backport-request

#1322 Handle error
  lib/Service/InstallService.php
Labels: backport-request

#1335 Fix command name
  lib/Service/ConfigureCheckService.php
Labels: backport-request

#1352 Read metadata of shared file
  lib/Migration/Version2040Date20211027183759.php
  lib/Service/PdfParserService.php
  lib/Service/SignFileService.php
  tests/Unit/Service/PdfParseServiceTest.php
Labels: bug, backport-request

#1354 Change icon color by theme
  lib/Listener/LoadSidebarListener.php
  src/style/icons.scss
  src/tab.js
Labels: bug, frontend, backport-request

#1356 Nothing to do
  src/views/FilesTab/LibresignTab.vue
Labels: frontend, backport-request

#1358 Changelog
  CHANGELOG.md
Labels: backport-request

#1372 Fix node version
  package-lock.json
  package.json
Labels: backport-request

#1374 Prevent errors during unit tests
  lib/Service/PdfParserService.php
  tests/Unit/TestCase.php
Labels: backport-request

#1376 Fix hide previous when haven't previous
  src/views/FilesTab/LibresignTab.vue
  src/views/SignDetail/partials/PageNavigation.vue
Labels: backport-request

#1378 Changelog
  CHANGELOG.md
Labels: backport-request

#1386 Update Application.php
  lib/AppInfo/Application.php
Labels: backport-request

#1399 Frontend improvements to generate root cert
  README.md
  lib/Service/AdminSignatureService.php
  src/views/Settings/RootCertificate.vue
Labels: backport-request
