Repository LibreSign/libresign, pull requests merged in 2023-04, with the labels that each got.

#1563 Make possible change the default user folder
  lib/Service/FolderService.php
  src/views/CreatePassword.vue
  src/views/Settings/DefaultUserFolder.vue
  src/views/Settings/Settings.vue
Labels: backport-request

#1561 Fix generate root certificate at the first time
  lib/Service/AdminSignatureService.php
Labels: backport-request

#1572 Update to nextcloud components
  src/assets/styles/loading.scss
  src/assets/styles/validation.scss
  src/views/Validation.vue
Labels: backport-request

#1598 Fix usage of initial state
  lib/Controller/PageController.php
  src/services/InitialStateService.js
Labels: backport-request

#1584 [WIP] Add identify method
  .github/workflows/behat.yml
  lib/Db/AccountFileMapper.php
  lib/Db/FileUser.php
  lib/Db/FileUserMapper.php
  lib/Helper/ValidateHelper.php
  lib/Migration/Version8000Date20230402103824.php
  lib/Service/SignFileService.php
  lib/Service/TFile.php
  tests/Unit/Helper/ValidateHelperTest.php
  tests/Unit/Service/SignFileServiceTest.php
  tests/integration/composer.json
  tests/integration/composer.lock
  tests/integration/config/behat.yml
  tests/integration/features/account/me.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/page/sign.feature
  tests/integration/features/sign/request.feature
Labels: enhancement, backport-request, php

#1609 Drop libresign cli
  composer.json
  composer.lock
  lib/Command/Base.php
  lib/Command/Install.php
  lib/Command/Uninstall.php
  lib/Controller/AdminController.php
  lib/Migration/Version8000Date20230410230327.php
  lib/Service/ConfigureCheckService.php
  lib/Service/InstallService.php
  lib/Service/PdfParserService.php
  src/views/Settings/DownloadBinaries.vue
  tests/Unit/Service/PdfParseServiceTest.php
  vendor-bin/php-coveralls/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: backport-request

#1613 Bump package
  tests/integration/composer.lock
Labels: backport-request

#1612 Refactor previous commit
  lib/Migration/Version8000Date20230410230327.php
  lib/Service/PdfParserService.php
  tests/Unit/Service/PdfParseServiceTest.php
Labels: backport-request

#1622 Lock friendsofphp/php-cs-fixer version
  lib/Service/TFile.php
  vendor-bin/coding-standard/composer.json
  vendor-bin/coding-standard/composer.lock
Labels: backport-request

#1621 Improvements at GitHub Actions
  .github/config.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
Labels: backport-request

#1620 fix: style preview signatur modal like canva style
  src/Components/Draw/Editor.vue
  src/Components/PreviewSignature/PreviewSignature.vue
  src/Components/PreviewSignature/index.js
  src/views/Account/partials/Signature.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: frontend, backport-request

#1636 Remove debug step
  tests/integration/features/page/sign.feature
Labels: backport-request

#1639 Add changelog
  CHANGELOG.md
Labels: backport-request

#1642 Fix usage of initialState
  src/App.vue
  src/helpers/SelectAction.js
  src/router/router.js
  src/services/InitialStateService.js
  src/services/InitialStateService.spec.js
  src/store/index.js
  src/store/modules/settings.js
  src/views/Account/partials/Documents.vue
  src/views/CreateUser.vue
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF/SignPDF.vue
Labels: backport-request, javascript

#1643 If is a prop, can't be a data.
  src/Components/PreviewSignature/PreviewSignature.vue
Labels: bug, backport-request, javascript

#1644 Add tests to validate identify method
  lib/Helper/ValidateHelper.php
  lib/Service/IdentifyMethodService.php
  lib/Service/MailService.php
  lib/Service/SignFileService.php
  tests/Unit/Helper/ValidateHelperTest.php
  tests/Unit/Service/SignFileServiceTest.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/page/sign_identify_default.feature
  tests/integration/features/page/sign_identify_token.feature
Labels: backend, backport-request
