Repository LibreSign/libresign, pull requests merged in 2024-01, with the labels that each got.

#2039 Follow the same rules as Nextcloud server
  .editorconfig
Labels: backport-request

#2037 Organize initial states
  lib/Controller/FileController.php
  lib/Controller/PageController.php
  lib/Controller/SignFileController.php
  lib/Db/FileMapper.php
  lib/Db/SignRequestMapper.php
  lib/Helper/ValidateHelper.php
  lib/Service/AccountService.php
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
  lib/Service/IdentifyMethod/Account.php
  lib/Service/IdentifyMethod/Email.php
  lib/Service/SignFileService.php
  src/App.vue
  src/Components/Request/VisibleElements.vue
  src/helpers/SelectAction.js
  src/router/index.js
  src/router/router.js
  src/store/index.js
  src/views/DefaultPageSuccess.vue
  src/views/SignPDF/SignPDF.vue
  src/views/Timeline/Timeline.vue
  tests/integration/features/account/create_to_sign.feature
  tests/integration/features/page/sign_identify_account.feature
  tests/integration/features/page/validate.feature
Labels: backport-request

#2050 Identify when the route has index.php
  src/router/router.js
Labels: backport-request

#2054 Revert previous commit
  src/router/router.js
Labels: backport-request

#2057 Remove hardcoded identify method name
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
Labels: backport-request

#2061 Disable execution of composer update every when install a new package
  composer.json
Labels: backport-request

#2063 Send params to next route
  src/router/router.js
Labels: backport-request

#2068 Fix method usage and name
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
Labels: backport-request

#2072 Send a best feedback to user when haven't permission at data folder
  lib/Service/InstallService.php
Labels: backport-request

#2076 Hide unauthorized actions and add validation action
  src/Components/Request/RequestSignature.vue
Labels: backport-request

#2075 Handle LibreSign exception
  lib/Controller/NotifyController.php
Labels: backport-request

#2074 Make possible save a file content into a file of different authenticated user
  lib/Service/SignFileService.php
  tests/Unit/Service/SignFileServiceTest.php
Labels: backport-request

#2080 Add feedback when got error server side
  lib/Service/TFile.php
  src/views/Request.vue
Labels: backport-request

#2081 Remove unused dependency and bump other dependencies
  package-lock.json
  package.json
Labels: backport-request

#2082 Fix error on close modal
  src/views/Request.vue
Labels: backport-request

#2083 Add loading icon
  src/views/Request.vue
Labels: backport-request

#2089 Enable send after error
  src/views/Request.vue
Labels: backport-request

#2084 Make possible create account using email
  lib/Controller/FileElementController.php
  lib/Controller/IdentifyAccountController.php
  lib/Controller/PageController.php
  lib/Db/IdentifyMethod.php
  lib/Db/SignRequestMapper.php
  lib/Helper/ValidateHelper.php
  lib/Middleware/Attribute/CanSignRequestUuid.php
  lib/Middleware/Attribute/RequireFileUserUuid.php
  lib/Migration/Version8000Date20230420125331.php
  lib/Migration/Version8000Date20231102215331.php
  lib/Service/FileService.php
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
  lib/Service/IdentifyMethod/Account.php
  lib/Service/IdentifyMethod/Email.php
  lib/Service/IdentifyMethod/IIdentifyMethod.php
  lib/Service/IdentifyMethodService.php
  lib/Service/SignFileService.php
  src/Components/Request/AccountOrEmail.vue
  src/Components/Request/IdentifyEmail.vue
  src/Components/Request/IdentifySigner.vue
  src/Components/Request/RequestSignature.vue
  src/Components/Request/SignerName.vue
  src/Components/Signers/Signer.vue
  src/views/Settings/IdentifierFactor.vue
  tests/integration/features/admin/initial_state.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/identify-account/search.feature
  tests/integration/features/page/index.feature
  tests/integration/features/sign/request.feature
Labels: backport-request

#1996 Display PDF document with lib
  lib/Controller/PageController.php
  lib/Helper/ValidateHelper.php
  lib/Service/FileElementService.php
  lib/Service/FileService.php
  package-lock.json
  package.json
  src/Components/Nextcloud/NcDialog/NcDialog.vue
  src/Components/PdfEditor/PdfEditor.vue
  src/Components/PdfEditor/Signature.vue
  src/Components/Request/VisibleElements.vue
  src/domains/sign/service.js
  webpack.config.js
Labels: frontend

#2106 Remove send reminder from herself
  src/Components/Request/RequestSignature.vue
Labels: backport-request

#2110 Remplace signed svg by LibreSign logo
  img/signed-icon.svg
  src/App.vue
Labels: backport-request

#2111 Fix var of signer uuid
  src/Components/Request/VisibleElements.vue
Labels: backport-request

#2114 Return removed logic
  src/App.vue
Labels: backport-request

#2116 Move template to begin
  src/Components/ProgressBar.vue
  src/Components/Request/SignDetail/partials/PageNavigation.vue
  src/views/Account/partials/Documents.vue
  src/views/Account/partials/Signatures.vue
  src/views/Documents/AccountValidation.vue
  src/views/SignPDF/_partials/ModalEmailManager.vue
  src/views/SignPDF/_partials/ModalSMSManager.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2118 Move template to begin
  src/Components/Draw/FileUpload.vue
  src/Components/Request/SignDetail/partials/Sidebar.vue
  src/views/Account/partials/Signature.vue
Labels: backport-request

#2120 Replace iframe by VuePdfEditor
  src/Components/PdfEditor/PdfEditor.vue
  src/Components/PdfEditor/Signature.vue
  src/views/SignPDF/SignPDF.vue
  src/views/SignPDF/_partials/ModalCreateSignature.vue
  src/views/SignPDF/_partials/PDFViewer.vue
Labels: backport-request

#2122 Fix the initial state name
  src/views/Account/partials/Documents.vue
Labels: backport-request

#2124 Readonly signatore
  src/Components/PdfEditor/PdfEditor.vue
  src/Components/PdfEditor/Signature.vue
Labels: backport-request

#2126 Covnert Draw component to modal
  src/Components/Draw/Draw.vue
  src/views/Account/partials/Signature.vue
Labels: backport-request

#2130 Rewrite sidebar at sign page
  lib/Controller/AccountController.php
  lib/Controller/PageController.php
  lib/Service/AccountService.php
  src/Components/PdfEditor/PdfEditor.vue
  src/Components/Request/VisibleElements.vue
  src/domains/sign/enum.js
  src/views/Account/Account.vue
  src/views/SignPDF/SignPDF.vue
  src/views/SignPDF/_partials/Sidebar.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2132 Save before sign
  src/Components/Request/VisibleElements.vue
Labels: backport-request

#1975 Create template for pull request
  .github/pull_request_template.md
Labels: enhancement

#2138 Add background to signature element
  src/Components/PdfEditor/Signature.vue
Labels: backport-request

#2140 Move loadMe to component
  src/domains/signatures/service.js
  src/views/Request.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2142 Refactor crud user signature
  lib/Controller/AccountController.php
  lib/Service/AccountService.php
  src/Components/Draw/Draw.vue
  src/domains/signatures/index.js
  src/domains/signatures/service.js
  src/views/Account/partials/Signature.vue
  src/views/Account/partials/Signatures.vue
Labels: backport-request

#2146 Show only email if the unique allowed identify method is email
  src/Components/Request/AccountOrEmail.vue
  src/Components/Request/IdentifySigner.vue
Labels: backport-request

#2148 Propagate change password status
  src/views/CreatePassword.vue
  src/views/SignPDF/_partials/ModalPasswordManager.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2152 Remove lodash-es and fix generation of settings array
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2154 Remove unused property
  lib/Service/RequestSignatureService.php
  tests/Unit/Service/RequestSignatureServiceTest.php
Labels: backport-request

#2156 Remove dead code
  .github/workflows/behat.yml
  appinfo/routes/routesFileController.php
  lib/Command/Configure/Check.php
  lib/Controller/FileController.php
  lib/Handler/TCPDILibresign.php
  lib/Service/AccountService.php
  lib/Service/ConfigureCheckService.php
  lib/Service/FileService.php
  tests/integration/features/account/me.feature
Labels: backport-request

#2159 Bugfix/refactor signature methods
  lib/Controller/PageController.php
  lib/Controller/SignFileController.php
  lib/Db/SignRequest.php
  lib/Db/SignRequestMapper.php
  lib/Helper/ValidateHelper.php
  lib/Middleware/Attribute/RequireSignRequestUuid.php
  lib/Service/FileService.php
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
  lib/Service/IdentifyMethod/Account.php
  lib/Service/IdentifyMethod/ClickToSign.php
  lib/Service/IdentifyMethod/Email.php
  lib/Service/IdentifyMethod/IIdentifyMethod.php
  lib/Service/IdentifyMethod/Password.php
  lib/Service/IdentifyMethodService.php
  lib/Service/MailService.php
  lib/Service/SignFileService.php
  lib/Service/SignatureMethodService.php
  src/views/SignPDF/_partials/ModalEmailManager.vue
  src/views/SignPDF/_partials/ModalSMSManager.vue
  src/views/SignPDF/_partials/Sign.vue
  tests/Api/Controller/SignFileControllerTest.php
  tests/Unit/Helper/ValidateHelperTest.php
  tests/integration/features/admin/initial_state.feature
  tests/integration/features/page/index.feature
Labels: backport-request

#2166 Make possible check if is me using account
  lib/Db/SignRequestMapper.php
Labels: backport-request

#2169 Use display name when is email
  src/Components/Request/IdentifySigner.vue
Labels: backport-request

#2171 Remove unused css
  src/views/CreatePassword.vue
  src/views/SignPDF/_partials/Sign.vue
Labels: backport-request

#2173 Remove unused var
  lib/Controller/SignFileController.php
  lib/Helper/ValidateHelper.php
Labels: backport-request

#2175 Disable create certificate when unauthenticated
  lib/Service/IdentifyMethod/Password.php
  lib/Service/SessionService.php
Labels: backport-request

#2179 Move logic to separated method
  lib/Controller/PageController.php
Labels: backport-request

#2180 Fix typing
  lib/Service/SignFileService.php
Labels: backport-request

#2182 Move validate to validate helper
  lib/Controller/LibresignTrait.php
  lib/Helper/ValidateHelper.php
  lib/Middleware/InjectionMiddleware.php
  lib/Service/SignFileService.php
Labels: backport-request

#2185 If we do a return, dont will check other proccess
  lib/Service/InstallService.php
Labels: backport-request

#2187 We don't neet to create root folder every time
  lib/Service/InstallService.php
Labels: backport-request

#2190 Fix linter
  src/Components/PdfEditor/PdfEditor.vue
Labels: backport-request

#2193 Fix css of menu
  src/App.vue
Labels: backport-request

#2198 Remove strange pattern at URL
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/CollectMetadata.vue
  src/views/Settings/DefaultUserFolder.vue
  src/views/Settings/ExpirationRules.vue
  src/views/Settings/IdentificationDocuments.vue
  src/views/Settings/LegalInformation.vue
  src/views/Settings/Validation.vue
Labels: backport-request

#2200 Don't show request sign when haven't permission to show
  src/App.vue
Labels: backport-request

#2203 Organize components
  src/Components/Draw/Draw.vue
  src/Components/File/Sidebar.vue
  src/Components/Request/SignDetail/partials/SignerRow.vue
  src/Components/Signers/Signer.vue
  src/router/router.js
  src/views/CreatePassword.vue
  src/views/Settings/AllowedGroups.vue
  src/views/Settings/CertificateCustonOptions.vue
  src/views/Settings/ExpirationRules.vue
  src/views/Settings/IdentificationDocuments.vue
  src/views/Settings/Validation.vue
Labels: backport-request

#2207 Use pinia and add file preview
  package-lock.json
  package.json
  src/App.vue
  src/Components/File/AppFilesTab.vue
  src/Components/File/File.vue
  src/Components/File/RightSidebar.vue
  src/Components/File/Sidebar.vue
  src/Components/Request/AccountOrEmail.vue
  src/Components/Request/RequestSignature.vue
  src/Components/Request/SignDetail/partials/Sidebar.vue
  src/Components/Request/VisibleElements.vue
  src/main.js
  src/store/files.js
  src/store/index.js
  src/store/modules/files.js
  src/store/modules/validate.js
  src/store/sidebar.js
  src/views/Request.vue
  src/views/SignPDF/SignPDF.vue
  src/views/Timeline/Timeline.vue
Labels: backport-request

#2209 Bump nextcloud dialogs and upgrade account documents
  lib/Controller/PageController.php
  lib/Db/AccountFileMapper.php
  lib/Helper/JSActions.php
  lib/Helper/ValidateHelper.php
  lib/Service/AccountService.php
  lib/Service/SignFileService.php
  package-lock.json
  package.json
  src/domains/documents/index.js
  src/domains/documents/service.js
  src/helpers/SelectAction.js
  src/helpers/path.js
  src/views/Account/partials/Documents.vue
  src/views/Documents/AccountValidation.vue
  src/views/Request.vue
  src/views/Settings/IdentificationDocuments.vue
Labels: backport-request

#2215 Replace class by icon
  src/App.vue
Labels: backport-request

#2227 Remove height after vue update
  src/Components/Request/VisibleElements.vue
Labels: backport-request

#2230 Fix CSP
  lib/Controller/PageController.php
Labels: backport-request

#2233 Sign-details div should be fixed on top
  src/Components/Request/VisibleElements.vue
Labels: backport-request

#2235 Prevent show incomplete view when is not incomplete
  src/router/router.js
Labels: backport-request

#2238 Organize code
  lib/Controller/AccountController.php
  lib/Service/AccountService.php
  lib/Service/FolderService.php
  lib/Service/IdentifyMethod/AbstractIdentifyMethod.php
  lib/Service/IdentifyMethod/Account.php
  lib/Service/IdentifyMethod/ClickToSign.php
  lib/Service/IdentifyMethod/Email.php
  lib/Service/IdentifyMethod/Password.php
  src/views/SignPDF/_partials/Sign.vue
  tests/Api/Controller/SignFileControllerTest.php
  tests/integration/features/account/create_to_sign.feature
  tests/integration/features/sign/request.feature
Labels: backport-request
